const PRIMARY_DIAGNOSIS = {
    0:"DIABETES",
    1:"GLOMERULONEPHRITIS",
    2:"HYPERTENSION",
    3:"CYSTIC_KIDNEY_DISEASE",
    4:"INTERSTITIAL_NEPHRITIS",
    5:"OBSTRUCTIVE_NEPHROPATHY",
    6:"OTHER",
    7:"UNKNOWN",
    8:"MISSING"
}